# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 09:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170615_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appreq',
            name='id',
        ),
        migrations.AddField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=0, max_length=5, primary_key=True, serialize=False, unique=True),
            preserve_default=False,
        ),
    ]
