# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 09:04
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20170615_1441'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appreq',
            name='id',
        ),
        migrations.AddField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('9de09505-f742-4bc0-8e00-dcd5d5053814'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
