# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 09:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170626_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='appreq',
            name='ID',
            field=models.CharField(blank=True, default=uuid.UUID('59faad4f-584e-4638-b057-f9eab43cecea'), max_length=100, unique=True),
        ),
    ]
