# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 09:24
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20170627_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('736ef121-6ed0-45cb-9d05-bbbf52077ba4'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
