# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20170627_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='appreq',
            name='value',
            field=models.IntegerField(default=0, max_length=1),
        ),
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('ffe71b15-df59-4abe-a3d2-3d3e417c2401'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
