# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 10:06
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170626_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('a82e89a5-2c5b-432e-b488-94ea71cee233'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
