# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 09:11
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20170629_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('0be831e4-75bf-4604-b75b-0f9d9f6ea206'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='appreq',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
