# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 04:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20170629_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appreq',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='appreq',
            name='start_date',
        ),
        migrations.AddField(
            model_name='appreq',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('0c06ad9e-66fb-46b9-9b28-09eec5af020a'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
