# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 05:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20170711_1009'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appreq',
            name='date',
        ),
        migrations.AddField(
            model_name='appreq',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appreq',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('7380a7d5-9ba6-4e47-b89f-f88edb689bb6'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
