# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 05:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20170711_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('5e9e7aa3-81c6-4579-ba06-d9b0ec6fc7e7'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='appreq',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
