# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 05:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20170711_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('67b1db5c-6b71-4e2e-9e9e-6a2ca35bf675'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='appreq',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
