# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 05:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20170711_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='appreq',
            name='myname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('0b7c0279-0307-483c-99fe-e5ffdbc77d43'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
