# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20170711_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('27ed32cd-a08c-4d61-ac27-b254ef36e08c'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='appreq',
            name='myname',
            field=models.CharField(max_length=50),
        ),
    ]
