# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 05:59
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20170711_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('e082015b-e9f9-4917-a4aa-db05c5f7aff1'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
