# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 11:27
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20170711_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('44f1fa5f-9523-4896-a832-1f430d0758e1'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
