# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 04:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20170713_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('5b7d5c80-285d-4d13-8537-12f8af9bcb20'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
