# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20170713_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('52f12010-daf2-41a5-b867-0d60a975529c'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
