# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_auto_20170713_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.UUIDField(default=uuid.UUID('85f253a9-14e1-4aaf-80a1-44a38b072e09'), primary_key=True, serialize=False, unique=True),
        ),
    ]
