# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 07:00
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_auto_20170713_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('92714ead-075a-4163-b67c-a0a151e61592'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
