# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 07:47
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_auto_20170713_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('9e8466c3-2623-4a6d-85e5-b27ef62e4236'), max_length=100, primary_key=True, serialize=False, unique=True),
        ),
    ]
