# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 08:55
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0029_auto_20170713_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='appreq',
            name='event_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('46e36fe6-0f57-499b-87e1-14501765c023'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
