# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 08:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20170717_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('b916b24e-951d-4fcb-afed-870dc8930063'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
