# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_auto_20170724_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('cb97ff24-dfe0-480f-bde3-050045f07e4f'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
