# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 15:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20170726_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreq',
            name='event_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
