# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 04:29
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20170726_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('1e9e5606-7284-11e7-a1e0-448500c2e63c'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
