# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 04:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20170727_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('1a1288a2-9d4f-42b6-92aa-a353c00b664e'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
    ]
