# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_auto_20170727_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.CharField(default=uuid.UUID('6615d2c9-7a3a-4d51-b8e7-71e1ceabdb1b'), max_length=50, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='appreq',
            name='event_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
