# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_auto_20170727_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreq',
            name='ID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
