# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-28 01:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_auto_20170728_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appreq',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
